cache-dir = "/tmp/.ruff_cache"
line-length = 88


# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
quote-style = "double"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
