name: Python Unit Tests

on:
  pull_request:
  push:
    branches: [main, 'releases/**']
  workflow_dispatch:

permissions: read-all

jobs:
  python_unit_tests:
    name: python_unit_tests
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Install dependencies
        run: |
          # We only have 1 external dependency other than pytest for now, so
          # list them here
          # If this changes, we may want to switch to a dependencies file of
          # some format
          python -m pip install --upgrade pip
          pip install pytest
          pip install networkx
          pip install PyYAML
      - name: Test with pytest
        run: |
          git config --global user.name 'Testing'
          git config --global user.email 'Testing'
          pytest -vv
